### PR TITLE
New test case for "Signature mismatch exception"

### PR DESCRIPTION
**Pull request by KvanTTT**
See #187

Please merge it after #189

### CODE REVIEW

**Comment by mkaring** [comment]
@KvanTTT: I merged #189. Seems this one still needs a rebase to work.

**Comment by KvanTTT** [comment]
Rebase is done. I've also remove not used parameter from `Run` signature.

**Comment by mkaring** [comment]
Thank you. I am looking into the issue.

**Comment by mkaring** [comment]
Was merged in #215

**Pull request closed without merging**
