### PR TITLE
Using cache during analysis phase

### LINKED ISSUE #373: Confusing the assembly is too slow.
I have the same issue with Catester. Please check this link https://github.com/yck1509/ConfuserEx/issues/600. I have been fix the issue in local code. Maybe it could merge to the current version.

### PR DESCRIPTION
**Pull request by mkaring**
fixes #373

### CODE REVIEW

**Comment by wmjordan** [comment]
This is really much faster!

**Comment by wmjordan** [comment]
Is it possible to create a new compilation of this PR after merging #377 ? I'd love to give it a test since #375 has been fixed.

**Comment by mkaring** [comment]
@wmjordan: [Here it is](https://ci.appveyor.com/project/mkaring/confuserex/builds/40028645/artifacts)

**Comment by wmjordan** [comment]
Thanks!

Just downloaded and put it up running.
Nothing went wrong so far.

**Comment by wmjordan** [comment]
Having been working with this version for two days, I am feeling good for this version.

**Pull request merged**
