### PR TITLE
Add config

### PR DESCRIPTION
**Pull request by iamwangxi**
In use, baseDir, prebePath, and outputDir change dynamically and need to be passed in from the command line. This submission supports these parameters to be passed in from the command line and take effect correctly.

### CODE REVIEW

**Comment by mkaring** [comment]
The command line parameters for the output directory and the probe paths are only supposed to take effect, if you are using a template project. Meaning if you pass the assembly you want to obfuscate to the CLI and the `*.crproj` file as last parameter.

I don't really see the point in overwriting anything if you want to explicitly execute one specific `*.crproj` file. Executing a project directly should always yield the correct results without additional parameters passed to the CLI.

What is the use case you are going for here?

**Comment by iamwangxi** [comment]
> The command line parameters for the output directory and the probe paths are only supposed to take effect, if you are using a template project. Meaning if you pass the assembly you want to obfuscate to the CLI and the `*.crproj` file as last parameter.
> 
> I don't really see the point in overwriting anything if you want to explicitly execute one specific `*.crproj` file. Executing a project directly should always yield the correct results without additional parameters passed to the CLI.
> 
> What is the use case you are going for here?

Mainly because we use a makefile template to generate corresponding makefiles for different products, and call ConfuserEx in the generated makefiles for obfuscation. In this case, the outputDir and probe path of each product are different, so they cannot be written directly in the `*.crproj` file.
By the way, in the obfuscation tool deepsea, these parameters are passed in through the command line.

**Comment by mkaring** [comment]
This sounds like the exact use case for the template mode of the CLI.

You call it like this:
```
Confuser.CLI.exe -o=<OutputDir> <Assembly1> [<Assembly2> …] <Template.crproj>
```

Using this the base directory is always the directory of `<Assembly1>`. This should fit nicely to what you are doing, doesn't it?

**Comment by iamwangxi** [comment]
> This sounds like the exact use case for the template mode of the CLI.
> 
> You call it like this:
> 
> ```
> Confuser.CLI.exe -o=<OutputDir> <Assembly1> [<Assembly2> …] <Template.crproj>
> ```
> 
> Using this the base directory is always the directory of `<Assembly1>`. This should fit nicely to what you are doing, doesn't it?

Sorry for the late reply. 

I tried to call the template mode many times, but I couldn't use it correctly. Could you give me an example?

For example, my OutputDir is `\dotfus`, baseDir is the current directory, and the probe contains `\Libs\test1` and `\Libs\test2`. How should I write a command to call the template mode?

( In addition, through debugging, I found that my command always enters` if (files.Count == 1 && Path.GetExtension(files[0]) == ".crproj")`, but it seems that it can be loaded correctly if entering `else`. )

**Comment by mkaring** [comment]
You should be able to call it like this:
```
C:\Path\To\Confuser.CLI.exe -o=dotfus C:\Project\mainAssembly.dll C:\Unrelated\Path\To\project.crproj
```

**Comment by iamwangxi** [comment]
> You should be able to call it like this:
> 
> ```
> C:\Path\To\Confuser.CLI.exe -o=dotfus C:\Project\mainAssembly.dll C:\Unrelated\Path\To\project.crproj
> ```
> 
> This will set the base dir in the project to "C:\Project", no matter what is written in the file.

Thanks Reply.
I tested the command you provided, this command can indeed specify outputDir. But there are still a few questions:
1. What is the relationship between the C:\Project\mainAssembly.dll in the command and the module (maybe modules) in the crproj file?
2. In this mode, how to input probe path from the command?
3. If we do not want to input outputDir from the command, but want to input the probe path from the command, how to write the command?

**Comment by mkaring** [comment]
> 1. What is the relationship between the C:\Project\mainAssembly.dll in the command and the module (maybe modules) in the crproj file?

In this case `C:\Project\` will be the base path. Meaning all paths to assemblies are resolved relative to `C:\Project\` unless they are provided as rooted paths.

> 2. In this mode, how to input probe path from the command?

You can't. It only uses the probe paths from the project file. But these paths are resolved relative to the base directory as well.

> 3. If we do not want to input outputDir from the command, but want to input the probe path from the command, how to write the command?

You need to specify the output directory. The template mode requires this.

**Comment by iamwangxi** [comment]
> > 1. What is the relationship between the C:\Project\mainAssembly.dll in the command and the module (maybe modules) in the crproj file?
> 
> In this case `C:\Project\` will be the base path. Meaning all paths to assemblies are resolved relative to `C:\Project\` unless they are provided as rooted paths.
> 
> > 1. In this mode, how to input probe path from the command?
> 
> You can't. It only uses the probe paths from the project file. But these paths are resolved relative to the base directory as well.
> 
> > 1. If we do not want to input outputDir from the command, but want to input the probe path from the command, how to write the command?
> 
> You need to specify the output directory. The template mode requires this.

That's it. This is also the original intention of my pull request.
We need to be able to choose to pass in the probe path from the command line because these values are different under different products, and the template mode does not support this feature.
This is our main requirement, and other obfuscation tools such as deepsea also support this function. Could you consider supporting this function?

**Comment by mkaring** [comment]
Sorry about that. I spoke false. You can set the probe paths in the template mode using the `-probe` Parameter. Those paths are added to the project.

So something like this should work for you:
```
C:\Path\To\Confuser.CLI.exe -o=dotfus -probe=C:\Probe\Path\1 -probe=C:\Another\Probe\Path C:\Project\mainAssembly.dll C:\Unrelated\Path\To\project.crproj
```

**Comment by iamwangxi** [comment]
> Sorry about that. I spoke false. You can set the probe paths in the template mode using the `-probe` Parameter. Those paths are added to the project.
> 
> So something like this should work for you:
> 
> ```
> C:\Path\To\Confuser.CLI.exe -o=dotfus -probe=C:\Probe\Path\1 -probe=C:\Another\Probe\Path C:\Project\mainAssembly.dll C:\Unrelated\Path\To\project.crproj
> ```

No problem. In fact, the template mode + probe parameter is enough to solve our problem. We will update our products according to the template model. Anyway, thank you very much.

**Pull request closed without merging**
