### PR TITLE
Fixed detection of blocking references across multiple assemblies

### LINKED ISSUE #379: Application crashed due to  `Failed to rename all targeted members, because the references are blocking each other`
- ConfuserEx Version:  1.6.0-alpha+52bdc4d8a5
- Target Framework: 4.7.2
- Operating System: Windows 10

Confuser displays the error during confusing (by yellow color):

```
Failed to rename all targeted members, because the references are blocking each other
```

But application crashes with a similar exception (these definitions match definitions from the abovementioned warning message):

```
System.TypeInitializationException: The type initializer for '_TxP0AsG8nfNdg13bierh6qBfDmUA' threw an exception. ---> System.TypeLoadException: Method '_5eWIIuvnOFv3kKlDFd5OIn0ZamC' in type '_RQbl3JXbfV9R9u8bfHFRVVZD5Kd' from assembly 'Test, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

This probably happens due to renaming protection with `renPublic = true` and related to cases when the method in base type implements an interface method for the derived type. `shortNames` option does not help.

I'll try to extract a minimal code sample later (it's quite complicated because of the big project and intertwined structure).

Is it possible to fix it (it worked in previous versions)? Or similar entities should be excluded from renaming?

### PR DESCRIPTION
**Pull request by mkaring**
fixes #379

### CODE REVIEW

**Comment by KvanTTT** [comment]
Unfortunately, another error appeared. I'm trying to figure out a reason.

**Comment by KvanTTT** [comment]
It seems like there is something wrong with crossreference properties renaming: 

```
System.TypeInitializationException: The type initializer for 'XXX' threw an exception. ---> System.TypeLoadException: Method 'get_Logger' in type '_YbY95Z8ef8fZ0hNbp9Bl6R07inP' from assembly 'YYY, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at _Lp1dCrrC6WtbAIfGTxJRjSwiWWb._Rq1CPdIekKPykD0eUP8zxKmKCnZ()
   at ZZZ..cctor()
   --- End of inner exception stack trace ---
   at WWW..ctor(SourceRepository , _bpohhAchrs62TGia1PpDFVZmNBn )
   at _U2UXRQIJWJL0xcUbI1mErr33wNJ.⁪‪‌‍⁮‍‪‪⁪‫⁪⁫‬‪‫⁯‌‭‍‫‏‌⁭⁪⁬⁪⁭⁫⁫‬​​⁯⁪‮⁮⁬‭‫‎‮(SourceRepository , _bpohhAchrs62TGia1PpDFVZmNBn )
   at _U2UXRQIJWJL0xcUbI1mErr33wNJ._71mdiZBHggKw2KWOFnjdtHe8hYu()
   at _U2UXRQIJWJL0xcUbI1mErr33wNJ._mjUwxZWUtQoByzaSlmVua9N6O9A()
```

But I still can not extract minimal reproducible example :(

**Comment by KvanTTT** [comment]
May be somebody else can test the assembly and check if it has errors?

**Comment by wmjordan** [comment]
The artifact on appveyor has been removed. How to obtain a binary?

**Comment by KvanTTT** [comment]
At least it's possible to build ConfuserEx manually.

**Comment by KvanTTT** [comment]
Generally, I accept this patch. Also, I think it makes sense to merge that request: https://github.com/mkaring/ConfuserEx/pull/385 since I was not able to extract another minimal sample that prevents correct obfuscation.

**Comment by mkaring** [comment]
So I'm merging that for now. The effect of the change is that renaming across assemblies that require inheritance issues to be resolved are generally blocked. Meaning no renaming will happen.
There is no other solution for this right now, because ConfuserEx is processing each assembly at this stage individually. It solve this properly it would have to join the assemblies together to obfuscate them as a unit.

**Pull request merged**
